### ISSUE TITLE
DLL placement

### ISSUE THREAD

**Issue by Sigillatus** [mattwright324/pdn-plugin-index#4]
Rick Brewster wrote on the forum: https://forums.getpaint.net/topic/116647-windows-store-plug-in-install-problem/?do=findComment&comment=572657

"Do not put files into the "root" installation folder. That is the wrong way to do things. Those instructions are wrong. "

I should weed out any offenders in the Index so we present a consistent narrative on plugin placement.

**Comment by rickbrew** [comment]
Thankfully I only saw a _very_ small number of plugins that actually did this. And now in 4.3/5.0+, those plugins literally won't work -- the loader just won't see their DLLs if they're in the main program directory.
